name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build-and-test:
   
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: find xcode
      run:  ls -n /Applications/ | grep Xcode*
    - name: Select Xcode
      run: sudo xcode-select -switch  /Applications/Xcode_15.0.1.app
    - name: Find simulators
      run: |
        sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
        ls -ltra /Applications/Xcode_*
        ls -ltra /Applications/Xcode_14.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/ 
        ls -ltra /Library/Developer/CoreSimulator/Profiles/Runtimes/

    - name: Build-and-test
      run: |
        xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
        xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4" ONLY_ACTIVE_ARCH=YES
